### ISSUE TITLE
Error in copy and paste form aother layer

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client-plugin-editing#10]
In this project I tried to make a copy and paste between a features of the Work areas and the layer of the buildings

https://v34.g3wsuite.it/it/map/demo-34/

When the form of the attributes is pre the id reports error and I can't save

In normal editing this id is automatic serial being the key field

![immagine](https://user-images.githubusercontent.com/4012899/193248260-3a67f21a-1175-4615-b0ed-02245e1be555.png)

**Comment by leolami** [comment]
iN REALITY THIS IS A GENERIC ERROR THAT ALSO APPEARS WHEN I CREATE A NEW FEATURES INDEPENDENTLY FROM COPY AND PASTE

**Comment by volterra79** [comment]
@leolami how can test copy and paste in https://v34.g3wsuite.it/it/map/demo-34/. Copy and paste is only in dev branch
