### ISSUE TITLE
Relational editing

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-client-plugin-editing#137]
### Checklist

- [x] I've searched through the [current issues](../issues) to make sure this feature hasn't been requested already.

### Motivation

New relationl editing function

- select more of parent features
- allow multi-editing on all the child records of all parent select features

### Suggested solution

Similar relational editing on all the child records of a single parent feature

**Comment by volterra79** [comment]
@leolami there is possible issue. When parent layer od selected feature has more than one relations. Which
 relations features we need to change?

**Comment by leolami** [comment]
The best solution would be to allow you to choose the relationship on which to operate and then proceed with the modification of the children of that relationship
