### ISSUE TITLE
Postgresql UUID data type not managed

### ISSUE THREAD

**Issue by zanollim** [g3w-suite/g3w-client-plugin-editing#38]
In case of layers with UUID data type (database Postgresql)  when you edit a feature, for example moving a point without edit any attribute, when you save the edits, the content of the UUID field is set to NULL (even if you do not change that specific attribute)

**Comment by volterra79** [comment]
@zanollim please upload data and a project to test it. Thanks

**Comment by zanollim** [comment]
Sorry, I can't reproduce the problem anymore, it was probably my mistake.
