### ISSUE TITLE
Editing Join 1:1

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client-plugin-editing#51]
![Screenshot from 2023-09-04 09-44-55](https://github.com/g3w-suite/g3w-client-plugin-editing/assets/1051694/72e40e9b-e5a0-4f4b-809d-ceaa690ead1e)

[RELAZIONI_MULTI_JOIN_EDITING.zip](https://github.com/g3w-suite/g3w-client-plugin-editing/files/12511346/RELAZIONI_MULTI_JOIN_EDITING.zip)

**Comment by Raruto** [comment]
@volterra79 has this been implemented yet?

**Comment by volterra79** [comment]
@Raruto we can close it
