### ISSUE TITLE
Erorr when click on Save All (Form disk icon)

### ISSUE THREAD

**Issue by volterra79** [g3w-suite/g3w-client-plugin-editing#78]
![Screenshot from 2023-12-11 15-17-15](https://github.com/g3w-suite/g3w-client-plugin-editing/assets/1051694/32f7ff09-c050-40ee-af29-aa5ae4da68e5)

After update form, if click on disk button **1**, we get an javascript error **2**

**Comment by Raruto** [comment]
@volterra79 Is this still a thing?

**Comment by volterra79** [comment]
@Raruto you can close it
