### ISSUE TITLE
Invalid context for `this._saveFeatures`  within `OpenFormTask::_saveFnc` ?

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-client-plugin-editing#84]
The following function appears to be unused:

https://github.com/g3w-suite/g3w-client-plugin-editing/blob/edd33b1dd02cdeaff676799942928f3ad899e96e/workflows/steps/tasks/openformtask.js#L234

because it is probably called with the wrong context in here (ref: `return function(`):

https://github.com/g3w-suite/g3w-client-plugin-editing/blob/edd33b1dd02cdeaff676799942928f3ad899e96e/workflows/steps/tasks/openformtask.js#L297-L300

https://github.com/g3w-suite/g3w-client-plugin-editing/blob/edd33b1dd02cdeaff676799942928f3ad899e96e/workflows/steps/tasks/openformtask.js#L359

**Comment by volterra79** [comment]
> The following function appears to be unused:
> 
> https://github.com/g3w-suite/g3w-client-plugin-editing/blob/edd33b1dd02cdeaff676799942928f3ad899e96e/workflows/steps/tasks/openformtask.js#L234
> 
> because it is probably called with the wrong context in here (ref: `return function(`):
> 
> https://github.com/g3w-suite/g3w-client-plugin-editing/blob/edd33b1dd02cdeaff676799942928f3ad899e96e/workflows/steps/tasks/openformtask.js#L297-L300
> 
> https://github.com/g3w-suite/g3w-client-plugin-editing/blob/edd33b1dd02cdeaff676799942928f3ad899e96e/workflows/steps/tasks/openformtask.js#L359

@Raruto it used https://github.com/g3w-suite/g3w-client-plugin-editing/blob/edd33b1dd02cdeaff676799942928f3ad899e96e/workflows/steps/tasks/openformtask.js#L297-L300 as you report.

**Comment by Raruto** [comment]
> it used 

@volterra79 vscode editor shows me as unusued..

The "this" context is wrong.

That means, `this._saveFnc(promise, context, inputs).bind(this)` doesn't work as you would excpect, because:

```js
proto._saveFnc = function(promise, context, inputs) { 
  return function(fields) {     // <-- this is NOT an arrow function (ie. () => { this._saveFeatures({ .. }); }),
    this._saveFeatures({ .. }); // so the "this._saveFeatures" no longer refers to class method
  }
}
```

**Comment by volterra79** [comment]
> > it used
> 
> @volterra79 vscode editor shows me as unusued..
> 
> The "this" context is wrong.
> 
> That means, `this._saveFnc(promise, context, inputs).bind(this)` doesn't work as you would excpect, because:
> 
> ```js
> proto._saveFnc = function(promise, context, inputs) { 
>   return function(fields) {     // <-- this is NOT an arrow function (ie. () => { this._saveFeatures({ .. }); }),
>     this._saveFeatures({ .. }); // so the "this._saveFeatures" no longer refers to class method
>   }
> }
> ```

@Raruto 

`cbk: this._saveFnc(promise, context, inputs).bind(this)` returns a function that is bind to `OpenFormTask`

It used by form save button to has a refence to openformtask instance.

Did you try to log this?

```js
proto._saveFnc = function(promise, context, inputs) {
  return function(fields) {
    //console.log(this)
    const session = context.session;
    this._saveFeatures({
      fields,
      promise,
      session,
      inputs
    });
  }
```
};

**Comment by Raruto** [comment]
Damn parentheses..

```js
this._saveFnc(promise, context, inputs).bind(this)
```

In your opinion, is there a simple way to rewrite it like the following?

```js
this._saveFnc(this, promise, context, inputs)
```

**Comment by volterra79** [comment]
> Damn parentheses..
> 
> ```js
> this._saveFnc(promise, context, inputs).bind(this)
> ```
> 
> In your opinion, is there a simple way to rewrite it like the following?
> 
> ```js
> this._saveFnc(this, promise, context, inputs)
> ```

@Raruto or just change

```js
this._saveFnc(promise, context, inputs)
```

```js
proto._saveFnc = function(promise, context, inputs) {
  return (fields) =>  {
    const session = context.session;
    this._saveFeatures({
      fields,
      promise,
      session,
      inputs
    });
  }
```

**Comment by volterra79** [comment]
@Raruto check commit https://github.com/g3w-suite/g3w-client-plugin-editing/pull/83/commits/d296ecb7599720dd80038b50465c8a3986f819a4

**Comment by volterra79** [comment]
@Raruto we can close it?
